Simulation = "BlsCosiBundleProtocol"
Servers = 1
Bf = 200
Rounds = 10
RunWait = "600s"
Suite = "bn256.adapter"

Hosts, FailingLeaves, MinDelay, MaxDelay, GossipTick, RumorPeers, ShutdownPeers, TreeMode
25, 0, 0.000, 0.000, 0.07, 3, 2, 0
25, 0, 0.005, 0.015, 0.07, 3, 2, 0
25, 0, 0.015, 0.025, 0.07, 3, 2, 0
25, 0, 0.025, 0.035, 0.07, 3, 2, 0
25, 0, 0.035, 0.045, 0.07, 3, 2, 0
25, 0, 0.045, 0.055, 0.07, 3, 2, 0
25, 0, 0.055, 0.065, 0.07, 3, 2, 0
25, 0, 0.065, 0.075, 0.07, 3, 2, 0
25, 0, 0.075, 0.085, 0.07, 3, 2, 0
25, 0, 0.085, 0.095, 0.07, 3, 2, 0
25, 0, 0.095, 0.105, 0.07, 3, 2, 0
25, 0, 0.105, 0.115, 0.07, 3, 2, 0
25, 0, 0.115, 0.125, 0.07, 3, 2, 0
25, 0, 0.125, 0.135, 0.07, 3, 2, 0
25, 0, 0.135, 0.145, 0.07, 3, 2, 0
25, 0, 0.145, 0.155, 0.07, 3, 2, 0
25, 0, 0.155, 0.165, 0.07, 3, 2, 0
25, 0, 0.165, 0.175, 0.07, 3, 2, 0
25, 0, 0.175, 0.185, 0.07, 3, 2, 0
25, 0, 0.185, 0.195, 0.07, 3, 2, 0
25, 0, 0.195, 0.205, 0.07, 3, 2, 0
25, 0, 0.205, 0.215, 0.07, 3, 2, 0
25, 0, 0.215, 0.225, 0.07, 3, 2, 0
25, 0, 0.225, 0.235, 0.07, 3, 2, 0
25, 0, 0.235, 0.245, 0.07, 3, 2, 0
25, 0, 0.245, 0.255, 0.07, 3, 2, 0
25, 0, 0.255, 0.265, 0.07, 3, 2, 0
25, 0, 0.265, 0.275, 0.07, 3, 2, 0
25, 0, 0.275, 0.285, 0.07, 3, 2, 0
25, 0, 0.285, 0.295, 0.07, 3, 2, 0
25, 0, 0.295, 0.305, 0.07, 3, 2, 0
25, 0, 0.305, 0.315, 0.07, 3, 2, 0
25, 0, 0.315, 0.325, 0.07, 3, 2, 0
25, 0, 0.325, 0.335, 0.07, 3, 2, 0
25, 0, 0.335, 0.345, 0.07, 3, 2, 0
25, 0, 0.345, 0.355, 0.07, 3, 2, 0
25, 0, 0.355, 0.365, 0.07, 3, 2, 0
25, 0, 0.365, 0.375, 0.07, 3, 2, 0
25, 0, 0.375, 0.385, 0.07, 3, 2, 0
25, 0, 0.385, 0.395, 0.07, 3, 2, 0
25, 0, 0.395, 0.405, 0.07, 3, 2, 0
25, 4, 0.000, 0.000, 0.07, 3, 2, 0
25, 4, 0.005, 0.015, 0.07, 3, 2, 0
25, 4, 0.015, 0.025, 0.07, 3, 2, 0
25, 4, 0.025, 0.035, 0.07, 3, 2, 0
25, 4, 0.035, 0.045, 0.07, 3, 2, 0
25, 4, 0.045, 0.055, 0.07, 3, 2, 0
25, 4, 0.055, 0.065, 0.07, 3, 2, 0
25, 4, 0.065, 0.075, 0.07, 3, 2, 0
25, 4, 0.075, 0.085, 0.07, 3, 2, 0
25, 4, 0.085, 0.095, 0.07, 3, 2, 0
25, 4, 0.095, 0.105, 0.07, 3, 2, 0
25, 4, 0.105, 0.115, 0.07, 3, 2, 0
25, 4, 0.115, 0.125, 0.07, 3, 2, 0
25, 4, 0.125, 0.135, 0.07, 3, 2, 0
25, 4, 0.135, 0.145, 0.07, 3, 2, 0
25, 4, 0.145, 0.155, 0.07, 3, 2, 0
25, 4, 0.155, 0.165, 0.07, 3, 2, 0
25, 4, 0.165, 0.175, 0.07, 3, 2, 0
25, 4, 0.175, 0.185, 0.07, 3, 2, 0
25, 4, 0.185, 0.195, 0.07, 3, 2, 0
25, 4, 0.195, 0.205, 0.07, 3, 2, 0
25, 4, 0.205, 0.215, 0.07, 3, 2, 0
25, 4, 0.215, 0.225, 0.07, 3, 2, 0
25, 4, 0.225, 0.235, 0.07, 3, 2, 0
25, 4, 0.235, 0.245, 0.07, 3, 2, 0
25, 4, 0.245, 0.255, 0.07, 3, 2, 0
25, 4, 0.255, 0.265, 0.07, 3, 2, 0
25, 4, 0.265, 0.275, 0.07, 3, 2, 0
25, 4, 0.275, 0.285, 0.07, 3, 2, 0
25, 4, 0.285, 0.295, 0.07, 3, 2, 0
25, 4, 0.295, 0.305, 0.07, 3, 2, 0
25, 4, 0.305, 0.315, 0.07, 3, 2, 0
25, 4, 0.315, 0.325, 0.07, 3, 2, 0
25, 4, 0.325, 0.335, 0.07, 3, 2, 0
25, 4, 0.335, 0.345, 0.07, 3, 2, 0
25, 4, 0.345, 0.355, 0.07, 3, 2, 0
25, 4, 0.355, 0.365, 0.07, 3, 2, 0
25, 4, 0.365, 0.375, 0.07, 3, 2, 0
25, 4, 0.375, 0.385, 0.07, 3, 2, 0
25, 4, 0.385, 0.395, 0.07, 3, 2, 0
25, 4, 0.395, 0.405, 0.07, 3, 2, 0
25, 8, 0.000, 0.000, 0.07, 3, 2, 0
25, 8, 0.005, 0.015, 0.07, 3, 2, 0
25, 8, 0.015, 0.025, 0.07, 3, 2, 0
25, 8, 0.025, 0.035, 0.07, 3, 2, 0
25, 8, 0.035, 0.045, 0.07, 3, 2, 0
25, 8, 0.045, 0.055, 0.07, 3, 2, 0
25, 8, 0.055, 0.065, 0.07, 3, 2, 0
25, 8, 0.065, 0.075, 0.07, 3, 2, 0
25, 8, 0.075, 0.085, 0.07, 3, 2, 0
25, 8, 0.085, 0.095, 0.07, 3, 2, 0
25, 8, 0.095, 0.105, 0.07, 3, 2, 0
25, 8, 0.105, 0.115, 0.07, 3, 2, 0
25, 8, 0.115, 0.125, 0.07, 3, 2, 0
25, 8, 0.125, 0.135, 0.07, 3, 2, 0
25, 8, 0.135, 0.145, 0.07, 3, 2, 0
25, 8, 0.145, 0.155, 0.07, 3, 2, 0
25, 8, 0.155, 0.165, 0.07, 3, 2, 0
25, 8, 0.165, 0.175, 0.07, 3, 2, 0
25, 8, 0.175, 0.185, 0.07, 3, 2, 0
25, 8, 0.185, 0.195, 0.07, 3, 2, 0
25, 8, 0.195, 0.205, 0.07, 3, 2, 0
25, 8, 0.205, 0.215, 0.07, 3, 2, 0
25, 8, 0.215, 0.225, 0.07, 3, 2, 0
25, 8, 0.225, 0.235, 0.07, 3, 2, 0
25, 8, 0.235, 0.245, 0.07, 3, 2, 0
25, 8, 0.245, 0.255, 0.07, 3, 2, 0
25, 8, 0.255, 0.265, 0.07, 3, 2, 0
25, 8, 0.265, 0.275, 0.07, 3, 2, 0
25, 8, 0.275, 0.285, 0.07, 3, 2, 0
25, 8, 0.285, 0.295, 0.07, 3, 2, 0
25, 8, 0.295, 0.305, 0.07, 3, 2, 0
25, 8, 0.305, 0.315, 0.07, 3, 2, 0
25, 8, 0.315, 0.325, 0.07, 3, 2, 0
25, 8, 0.325, 0.335, 0.07, 3, 2, 0
25, 8, 0.335, 0.345, 0.07, 3, 2, 0
25, 8, 0.345, 0.355, 0.07, 3, 2, 0
25, 8, 0.355, 0.365, 0.07, 3, 2, 0
25, 8, 0.365, 0.375, 0.07, 3, 2, 0
25, 8, 0.375, 0.385, 0.07, 3, 2, 0
25, 8, 0.385, 0.395, 0.07, 3, 2, 0
25, 8, 0.395, 0.405, 0.07, 3, 2, 0
