Simulation = "BlsCosiBundleProtocol"
Servers = 1
Bf = 200
Rounds = 20
RunWait = "600s"
Suite = "bn256.adapter"

Hosts, FailingLeaves, MinDelay, MaxDelay, GossipTick, RumorPeers, ShutdownPeers, TreeMode
25, 0, 0.095, 0.105, 0.01, 3, 2, 1
25, 0, 0.095, 0.105, 0.015, 3, 2, 1
25, 0, 0.095, 0.105, 0.02, 3, 2, 1
25, 0, 0.095, 0.105, 0.025, 3, 2, 1
25, 0, 0.095, 0.105, 0.03, 3, 2, 1
25, 0, 0.095, 0.105, 0.035, 3, 2, 1
25, 0, 0.095, 0.105, 0.04, 3, 2, 1
25, 0, 0.095, 0.105, 0.05, 3, 2, 1
25, 0, 0.095, 0.105, 0.06, 3, 2, 1
25, 0, 0.095, 0.105, 0.07, 3, 2, 1
25, 0, 0.095, 0.105, 0.08, 3, 2, 1
25, 0, 0.095, 0.105, 0.09, 3, 2, 1
25, 0, 0.095, 0.105, 0.10, 3, 2, 1
25, 0, 0.095, 0.105, 0.11, 3, 2, 1
25, 0, 0.095, 0.105, 0.12, 3, 2, 1
25, 0, 0.095, 0.105, 0.13, 3, 2, 1
25, 0, 0.095, 0.105, 0.14, 3, 2, 1
25, 0, 0.095, 0.105, 0.15, 3, 2, 1
25, 0, 0.095, 0.105, 0.16, 3, 2, 1
25, 0, 0.095, 0.105, 0.17, 3, 2, 1
25, 0, 0.095, 0.105, 0.18, 3, 2, 1
25, 0, 0.095, 0.105, 0.19, 3, 2, 1
25, 0, 0.095, 0.105, 0.20, 3, 2, 1
25, 0, 0.095, 0.105, 0.21, 3, 2, 1
25, 0, 0.095, 0.105, 0.22, 3, 2, 1
25, 0, 0.095, 0.105, 0.23, 3, 2, 1
25, 0, 0.095, 0.105, 0.24, 3, 2, 1
25, 0, 0.095, 0.105, 0.25, 3, 2, 1
25, 4, 0.095, 0.105, 0.01, 3, 2, 1
25, 4, 0.095, 0.105, 0.015, 3, 2, 1
25, 4, 0.095, 0.105, 0.02, 3, 2, 1
25, 4, 0.095, 0.105, 0.025, 3, 2, 1
25, 4, 0.095, 0.105, 0.03, 3, 2, 1
25, 4, 0.095, 0.105, 0.035, 3, 2, 1
25, 4, 0.095, 0.105, 0.04, 3, 2, 1
25, 4, 0.095, 0.105, 0.05, 3, 2, 1
25, 4, 0.095, 0.105, 0.06, 3, 2, 1
25, 4, 0.095, 0.105, 0.07, 3, 2, 1
25, 4, 0.095, 0.105, 0.08, 3, 2, 1
25, 4, 0.095, 0.105, 0.09, 3, 2, 1
25, 4, 0.095, 0.105, 0.10, 3, 2, 1
25, 4, 0.095, 0.105, 0.11, 3, 2, 1
25, 4, 0.095, 0.105, 0.12, 3, 2, 1
25, 4, 0.095, 0.105, 0.13, 3, 2, 1
25, 4, 0.095, 0.105, 0.14, 3, 2, 1
25, 4, 0.095, 0.105, 0.15, 3, 2, 1
25, 4, 0.095, 0.105, 0.16, 3, 2, 1
25, 4, 0.095, 0.105, 0.17, 3, 2, 1
25, 4, 0.095, 0.105, 0.18, 3, 2, 1
25, 4, 0.095, 0.105, 0.19, 3, 2, 1
25, 4, 0.095, 0.105, 0.20, 3, 2, 1
25, 4, 0.095, 0.105, 0.21, 3, 2, 1
25, 4, 0.095, 0.105, 0.22, 3, 2, 1
25, 4, 0.095, 0.105, 0.23, 3, 2, 1
25, 4, 0.095, 0.105, 0.24, 3, 2, 1
25, 4, 0.095, 0.105, 0.25, 3, 2, 1
25, 8, 0.095, 0.105, 0.01, 3, 2, 1
25, 8, 0.095, 0.105, 0.015, 3, 2, 1
25, 8, 0.095, 0.105, 0.02, 3, 2, 1
25, 8, 0.095, 0.105, 0.025, 3, 2, 1
25, 8, 0.095, 0.105, 0.03, 3, 2, 1
25, 8, 0.095, 0.105, 0.035, 3, 2, 1
25, 8, 0.095, 0.105, 0.04, 3, 2, 1
25, 8, 0.095, 0.105, 0.05, 3, 2, 1
25, 8, 0.095, 0.105, 0.06, 3, 2, 1
25, 8, 0.095, 0.105, 0.07, 3, 2, 1
25, 8, 0.095, 0.105, 0.08, 3, 2, 1
25, 8, 0.095, 0.105, 0.09, 3, 2, 1
25, 8, 0.095, 0.105, 0.10, 3, 2, 1
25, 8, 0.095, 0.105, 0.11, 3, 2, 1
25, 8, 0.095, 0.105, 0.12, 3, 2, 1
25, 8, 0.095, 0.105, 0.13, 3, 2, 1
25, 8, 0.095, 0.105, 0.14, 3, 2, 1
25, 8, 0.095, 0.105, 0.15, 3, 2, 1
25, 8, 0.095, 0.105, 0.16, 3, 2, 1
25, 8, 0.095, 0.105, 0.17, 3, 2, 1
25, 8, 0.095, 0.105, 0.18, 3, 2, 1
25, 8, 0.095, 0.105, 0.19, 3, 2, 1
25, 8, 0.095, 0.105, 0.20, 3, 2, 1
25, 8, 0.095, 0.105, 0.21, 3, 2, 1
25, 8, 0.095, 0.105, 0.22, 3, 2, 1
25, 8, 0.095, 0.105, 0.23, 3, 2, 1
25, 8, 0.095, 0.105, 0.24, 3, 2, 1
25, 8, 0.095, 0.105, 0.25, 3, 2, 1
