Simulation = "BlsCosiBundleProtocol"
Servers = 1
Bf = 200
Rounds = 40
RunWait = "600s"
Suite = "bn256.adapter"

Hosts, FailingLeaves, MinDelay, MaxDelay, GossipTick, RumorPeers, ShutdownPeers, TreeMode
25, 0, 0.095, 0.105, 0.07, 3, 0, 1
25, 0, 0.085, 0.115, 0.07, 3, 0, 1
25, 0, 0.075, 0.125, 0.07, 3, 0, 1
25, 0, 0.065, 0.135, 0.07, 3, 0, 1
25, 0, 0.055, 0.145, 0.07, 3, 0, 1
25, 0, 0.045, 0.155, 0.07, 3, 0, 1
25, 0, 0.035, 0.165, 0.07, 3, 0, 1
25, 0, 0.025, 0.175, 0.07, 3, 0, 1
25, 0, 0.015, 0.185, 0.07, 3, 0, 1
25, 0, 0.005, 0.195, 0.07, 3, 0, 1
25, 4, 0.095, 0.105, 0.07, 3, 0, 1
25, 4, 0.085, 0.115, 0.07, 3, 0, 1
25, 4, 0.075, 0.125, 0.07, 3, 0, 1
25, 4, 0.065, 0.135, 0.07, 3, 0, 1
25, 4, 0.055, 0.145, 0.07, 3, 0, 1
25, 4, 0.045, 0.155, 0.07, 3, 0, 1
25, 4, 0.035, 0.165, 0.07, 3, 0, 1
25, 4, 0.025, 0.175, 0.07, 3, 0, 1
25, 4, 0.015, 0.185, 0.07, 3, 0, 1
25, 4, 0.005, 0.195, 0.07, 3, 0, 1
25, 8, 0.095, 0.105, 0.07, 3, 0, 1
25, 8, 0.085, 0.115, 0.07, 3, 0, 1
25, 8, 0.075, 0.125, 0.07, 3, 0, 1
25, 8, 0.065, 0.135, 0.07, 3, 0, 1
25, 8, 0.055, 0.145, 0.07, 3, 0, 1
25, 8, 0.045, 0.155, 0.07, 3, 0, 1
25, 8, 0.035, 0.165, 0.07, 3, 0, 1
25, 8, 0.025, 0.175, 0.07, 3, 0, 1
25, 8, 0.015, 0.185, 0.07, 3, 0, 1
25, 8, 0.005, 0.195, 0.07, 3, 0, 1
